### ISSUE TITLE
Terminal doesn't work.

### ISSUE THREAD

**Issue by SillentAssembly** [consulo/consulo-terminal#1]
On clicking to open terminal
http://prnt.sc/ee6pag
[Terminal plugin error.txt](https://github.com/consulo/consulo-terminal/files/805211/Terminal.plugin.error.txt)

**Comment by VISTALL** [comment]
Hi. I will check maybe today. Windows 7 (64 bit) ?

**Comment by VISTALL** [comment]
Hi. It fixed in nightly channel. I am working on moving nightly to release (i have bug with macos update)

Thanks
